---
ci:
  # Skip hadolint in pre-commit CI because it requires hadolint executable.
  skip:
    - dotenv-linter
    - hadolint

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude_types: [markdown] # For line breaks.
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: mixed-line-ending
      - id: check-executables-have-shebangs

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.33.0
    hooks:
      - id: yamllint
        args:
          - -c=.yamllint.yaml

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint
        args:
          - --config=.markdownlint.yaml
          - --fix # Fix basic errors.

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.1-beta
    hooks:
      - id: hadolint
        args:
          - --config=.hadolint.yaml

  - repo: local
    hooks:
      - id: dotenv-linter
        name: dotenv-linter
        entry: dotenv-linter
        language: system
        files: \.env$
