---
###########################################
# These are the rules used for            #
# linting all the yaml files in the stack #
# NOTE:                                   #
# You can disable line with:              #
# # yamllint disable-line                 #
###########################################
extends: default
rules:
  comments:
    # Used to follow prettier standard:
    # https://github.com/prettier/prettier/pull/10926
    min-spaces-from-content: 1
  truthy:
    allowed-values: ["true", "false", "on"]
